{
 "title": "Import Stats Over time",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chains",
    "query": "select distinct chain from product where chain not in ('harmony', 'heco')"
   },
   { "name": "dashboard_eol", "query": "true, false" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Global work", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$chains investments: Import Stats ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "with last_chain_stats as (\n  SELECT\n    chain,\n    import_type,\n    last(errors_count, datetime) as errors_count,\n    last(not_covered_yet, datetime) as not_covered_yet,\n    last(success_count, datetime) as success_count,\n    last(errors_count, datetime) + last(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:investment', 'product:share-rate')\n  group by 1,2\n), first_chain_stats as (\n  SELECT\n    chain,\n    import_type,\n    first(errors_count, datetime) as errors_count,\n    first(not_covered_yet, datetime) as not_covered_yet,\n    first(success_count, datetime) as success_count,\n    first(errors_count, datetime) + first(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:investment', 'product:share-rate')\n  group by 1,2\n)\nselect \n  sum(f.errors_count) as errors_count_before,\n  sum(l.errors_count) as errors_count_now,\n  case when sum(f.errors_count) = 0 then 0 else (sum(l.errors_count) - sum(f.errors_count))/sum(f.errors_count) end as error_progress,\n  --sum(f.success_count) as success_count_before,\n  --sum(l.success_count) as success_count_now,\n  --case when sum(f.success_count) = 0 then 0 else (sum(l.success_count) - sum(f.success_count))/sum(f.success_count) end as success_count_progress,\n  sum(f.not_covered_yet) as not_covered_yet_before,\n  sum(l.not_covered_yet) as not_covered_yet_now,\n  case when sum(f.not_covered_yet) = 0 then 0 else (sum(l.not_covered_yet) - sum(f.not_covered_yet))/sum(f.not_covered_yet) end as not_covered_yet_progress,\n  sum(f.total_work) as total_work_before,\n  sum(l.total_work) as total_work_now,\n  case when sum(f.total_work) = 0 then 0 else (sum(l.total_work) - sum(f.total_work))/sum(f.total_work) end as total_work_progress\nfrom last_chain_stats l\n left join first_chain_stats f on l.chain = f.chain and l.import_type = f.import_type"
    }
   ]
  },
  {
   "title": "$chains investments & share rate total work",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "with last_metrics as (\n  SELECT\n    chain,\n    import_type,\n    last(errors_count, datetime) as errors_count,\n    last(not_covered_yet, datetime) as not_covered_yet,\n    last(success_count, datetime) as success_count,\n    last(errors_count, datetime) + last(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:investment', 'product:share-rate')\n  group by 1,2\n)\nselect \n  chain,\n  sum(total_work) as total_work\nfrom last_metrics\ngroup by 1"
    }
   ]
  },
  {
   "title": "$chains investments total work",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "with last_metrics as (\n  SELECT\n    chain,\n    import_type,\n    last(errors_count, datetime) as errors_count,\n    last(not_covered_yet, datetime) as not_covered_yet,\n    last(success_count, datetime) as success_count,\n    last(errors_count, datetime) + last(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:investment')\n  group by 1,2\n)\nselect \n  chain,\n  sum(total_work) as total_work\nfrom last_metrics\ngroup by 1"
    }
   ]
  },
  {
   "title": "$chains share rate total work",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "with last_metrics as (\n  SELECT\n    chain,\n    import_type,\n    last(errors_count, datetime) as errors_count,\n    last(not_covered_yet, datetime) as not_covered_yet,\n    last(success_count, datetime) as success_count,\n    last(errors_count, datetime) + last(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ( 'product:share-rate')\n  group by 1,2\n)\nselect \n  chain,\n  sum(total_work) as total_work\nfrom last_metrics\ngroup by 1"
    }
   ]
  },
  {
   "title": "$chains investments & share rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with stats as (\n  SELECT\n    datetime,\n    sum(errors_count) as errors_count,\n    sum(success_count) as success_count,\n    sum(not_covered_yet) as not_covered_yet,\n    sum(errors_count) + sum(not_covered_yet) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:investment', 'product:share-rate')\n  group by 1\n)\nselect \n  time_bucket('$interval'::interval, datetime) AS \"time\",\n  min(errors_count) as min_errors_count,\n  avg(errors_count) as avg_errors_count,\n  max(errors_count) as max_errors_count,\n  min(not_covered_yet) as min_not_covered_yet,\n  avg(not_covered_yet) as avg_not_covered_yet,\n  max(not_covered_yet) as max_not_covered_yet,\n  min(total_work) as min_total_work,\n  avg(total_work) as avg_total_work,\n  max(total_work) as max_total_work\nfrom stats\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$chains investments & share rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  chain,\n  datetime AS \"time\",\n  --sum(errors_count) as errors_count,\n  --success_count as success_count,\n  --sum(not_covered_yet) as not_covered_yet,\n  sum(errors_count) + sum(not_covered_yet) as total_work\nFROM import_state_metrics_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n  and import_type in ('product:investment', 'product:share-rate')\ngroup by 1, 2\nORDER BY 2"
    }
   ]
  },
  { "title": "By type of import", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$chains investments: Import Stats ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "with last_chain_stats as (\n  SELECT\n    chain,\n    last(errors_count, datetime) as errors_count,\n    last(not_covered_yet, datetime) as not_covered_yet,\n    last(success_count, datetime) as success_count,\n    last(errors_count, datetime) + last(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type = 'product:investment'\n  group by 1\n), first_chain_stats as (\n  SELECT\n    chain,\n    first(errors_count, datetime) as errors_count,\n    first(not_covered_yet, datetime) as not_covered_yet,\n    first(success_count, datetime) as success_count,\n    first(errors_count, datetime) + first(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type = 'product:investment'\n  group by 1\n)\nselect \n  sum(f.errors_count) as errors_count_before,\n  sum(l.errors_count) as errors_count_now,\n  case when sum(f.errors_count) = 0 then 0 else (sum(l.errors_count) - sum(f.errors_count))/sum(f.errors_count) end as error_progress,\n  --sum(f.success_count) as success_count_before,\n  --sum(l.success_count) as success_count_now,\n  --case when sum(f.success_count) = 0 then 0 else (sum(l.success_count) - sum(f.success_count))/sum(f.success_count) end as success_count_progress,\n  sum(f.not_covered_yet) as not_covered_yet_before,\n  sum(l.not_covered_yet) as not_covered_yet_now,\n  case when sum(f.not_covered_yet) = 0 then 0 else (sum(l.not_covered_yet) - sum(f.not_covered_yet))/sum(f.not_covered_yet) end as not_covered_yet_progress,\n  sum(f.total_work) as total_work_before,\n  sum(l.total_work) as total_work_now,\n  case when sum(f.total_work) = 0 then 0 else (sum(l.total_work) - sum(f.total_work))/sum(f.total_work) end as total_work_progress\nfrom last_chain_stats l\n left join first_chain_stats f on l.chain = f.chain"
    }
   ]
  },
  {
   "title": "$chains investments: Import Stats ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "with last_chain_stats as (\n  SELECT\n    chain,\n    last(errors_count, datetime) as errors_count,\n    last(not_covered_yet, datetime) as not_covered_yet,\n    last(success_count, datetime) as success_count,\n    last(errors_count, datetime) + last(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type = 'product:share-rate'\n  group by 1\n), first_chain_stats as (\n  SELECT\n    chain,\n    first(errors_count, datetime) as errors_count,\n    first(not_covered_yet, datetime) as not_covered_yet,\n    first(success_count, datetime) as success_count,\n    first(errors_count, datetime) + first(not_covered_yet, datetime) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type = 'product:share-rate'\n  group by 1\n)\nselect \n  sum(f.errors_count) as errors_count_before,\n  sum(l.errors_count) as errors_count_now,\n  case when sum(f.errors_count) = 0 then 0 else (sum(l.errors_count) - sum(f.errors_count))/sum(f.errors_count) end as error_progress,\n  --sum(f.success_count) as success_count_before,\n  --sum(l.success_count) as success_count_now,\n  --case when sum(f.success_count) = 0 then 0 else (sum(l.success_count) - sum(f.success_count))/sum(f.success_count) end as success_count_progress,\n  sum(f.not_covered_yet) as not_covered_yet_before,\n  sum(l.not_covered_yet) as not_covered_yet_now,\n  case when sum(f.not_covered_yet) = 0 then 0 else (sum(l.not_covered_yet) - sum(f.not_covered_yet))/sum(f.not_covered_yet) end as not_covered_yet_progress,\n  sum(f.total_work) as total_work_before,\n  sum(l.total_work) as total_work_now,\n  case when sum(f.total_work) = 0 then 0 else (sum(l.total_work) - sum(f.total_work))/sum(f.total_work) end as total_work_progress\nfrom last_chain_stats l\n left join first_chain_stats f on l.chain = f.chain"
    }
   ]
  },
  {
   "title": "$chains investments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with stats as (\n  SELECT\n    datetime,\n    sum(errors_count) as errors_count,\n    sum(success_count) as success_count,\n    sum(not_covered_yet) as not_covered_yet,\n    sum(errors_count) + sum(not_covered_yet) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:investment')\n  group by 1\n)\nselect \n  time_bucket('$interval'::interval, datetime) AS \"time\",\n  min(errors_count) as min_errors_count,\n  avg(errors_count) as avg_errors_count,\n  max(errors_count) as max_errors_count,\n  min(not_covered_yet) as min_not_covered_yet,\n  avg(not_covered_yet) as avg_not_covered_yet,\n  max(not_covered_yet) as max_not_covered_yet,\n  min(total_work) as min_total_work,\n  avg(total_work) as avg_total_work,\n  max(total_work) as max_total_work\nfrom stats\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$chains share rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with stats as (\n  SELECT\n    datetime,\n    sum(errors_count) as errors_count,\n    sum(success_count) as success_count,\n    sum(not_covered_yet) as not_covered_yet,\n    sum(errors_count) + sum(not_covered_yet) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:share-rate')\n  group by 1\n)\nselect \n  time_bucket('$interval'::interval, datetime) AS \"time\",\n  min(errors_count) as min_errors_count,\n  avg(errors_count) as avg_errors_count,\n  max(errors_count) as max_errors_count,\n  min(not_covered_yet) as min_not_covered_yet,\n  avg(not_covered_yet) as avg_not_covered_yet,\n  max(not_covered_yet) as max_not_covered_yet,\n  min(total_work) as min_total_work,\n  avg(total_work) as avg_total_work,\n  max(total_work) as max_total_work\nfrom stats\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  { "title": "$chains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "chains" },
  {
   "title": "$chains investments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with stats as (\n  SELECT\n    datetime,\n    sum(errors_count) as errors_count,\n    sum(success_count) as success_count,\n    sum(not_covered_yet) as not_covered_yet,\n    sum(errors_count) + sum(not_covered_yet) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:investment')\n  group by 1\n)\nselect \n  time_bucket('$interval'::interval, datetime) AS \"time\",\n  min(errors_count) as min_errors_count,\n  avg(errors_count) as avg_errors_count,\n  max(errors_count) as max_errors_count,\n  min(not_covered_yet) as min_not_covered_yet,\n  avg(not_covered_yet) as avg_not_covered_yet,\n  max(not_covered_yet) as max_not_covered_yet,\n  min(total_work) as min_total_work,\n  avg(total_work) as avg_total_work,\n  max(total_work) as max_total_work\nfrom stats\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$chains share rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with stats as (\n  SELECT\n    datetime,\n    sum(errors_count) as errors_count,\n    sum(success_count) as success_count,\n    sum(not_covered_yet) as not_covered_yet,\n    sum(errors_count) + sum(not_covered_yet) as total_work\n  FROM import_state_metrics_ts\n  WHERE\n    $__timeFilter(datetime)\n    and chain in ($chains)\n    and eol in (select unnest(Array[$dashboard_eol]::boolean[]))\n    and import_type in ('product:share-rate')\n  group by 1\n)\nselect \n  time_bucket('$interval'::interval, datetime) AS \"time\",\n  min(errors_count) as min_errors_count,\n  avg(errors_count) as avg_errors_count,\n  max(errors_count) as max_errors_count,\n  min(not_covered_yet) as min_not_covered_yet,\n  avg(not_covered_yet) as avg_not_covered_yet,\n  max(not_covered_yet) as max_not_covered_yet,\n  min(total_work) as min_total_work,\n  avg(total_work) as avg_total_work,\n  max(total_work) as max_total_work\nfrom stats\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last 20 Rpc Errors for this chain",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT datetime, rpc_url, request, response\nFROM rpc_error_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chains)\nORDER BY 1 desc\nlimit 20"
    }
   ]
  }
 ]
}