{
 "title": "Raw data completeness check",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from data_raw.vault"
   },
   {
    "name": "vault_id",
    "query": "select distinct vault_id from data_raw.vault where chain in ($chain)"
   }
  ]
 },
 "panels": [
  {
   "title": "Vault data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vaults",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  chain, format_evm_address(token_address) as token_address, vault_id, token_name,\n  format_evm_address(want_address) as want_address, want_decimals, want_price_oracle_id, end_of_life, assets_oracle_id\nFROM data_raw.vault\nWHERE\n  chain in ($chain)\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Raw data debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Erc20 transfer dates",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  v.chain, format_evm_address(token_address) as contract_address, v.vault_id, min(datetime) as first_erc20_transfer, max(datetime) as last_erc20_transfer\nFROM data_raw.vault v\n  left join data_raw.erc20_balance_diff_ts b on b.contract_address = v.token_address\nWHERE\n  v.chain in ($chain)\n  and v.vault_id in ($vault_id)\ngroup by 1,2,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PPFS dates",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  v.chain, format_evm_address(token_address) as contract_address, v.vault_id, min(datetime) as first_ppfs, max(datetime) as last_ppfs\nFROM data_raw.vault v\n  left join data_raw.vault_ppfs_ts p on p.contract_address = v.token_address\nWHERE\n  v.chain in ($chain)\n  and v.vault_id in ($vault_id)\ngroup by 1,2,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Prices debug",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  v.want_price_oracle_id as oracle_id, format_evm_address(v.token_address) as contract_address, v.vault_id, min(datetime) as first_price, max(datetime) as last_price\nFROM data_raw.vault v\n  left join data_raw.oracle_price_ts o on o.oracle_id = v.want_price_oracle_id\nWHERE\n  v.vault_id in ($vault_id)\ngroup by 1,2,3\nORDER BY 1"
    }
   ]
  }
 ]
}