{
 "title": "raw data Vault debug",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from data_raw.vault"
   },
   {
    "name": "vault_id",
    "query": "select distinct vault_id from data_raw.vault where chain = '$chain'"
   }
  ]
 },
 "panels": [
  {
   "title": "vault data",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  vault_id, format_evm_address(token_address) as token_address\nFROM\n  data_raw.vault\nWHERE\n  vault_id = '$vault_id'\n"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$vault_id data_derived.erc20_contract_balance_diff_4h_ts",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  balance_after\nFROM data_derived.erc20_contract_balance_diff_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and contract_address in (\n    select token_address\n    from data_raw.vault\n    where vault_id = '$vault_id'\n  )\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$vault_id data_derived.vault_ppfs_4h_ts",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  avg_ppfs\nFROM data_derived.vault_ppfs_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and contract_address in (\n    select token_address\n    from data_raw.vault\n    where vault_id = '$vault_id'\n  )\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$vault_id data_derived.vault_ppfs_4h_ts",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  avg_usd_value\nFROM data_derived.oracle_price_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and oracle_id in (\n    select want_price_oracle_id\n    from data_raw.vault\n    where vault_id = '$vault_id'\n  )\nORDER BY 1"
    }
   ]
  }
 ]
}