{
 "title": "Investor USD 4h Overview",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "investor_address",
    "query": "0x18913656c387613f6D0a1bFF7365C335C0069e69"
   }
  ]
 },
 "panels": [
  { "title": "Portfolio USD Value", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total PTF $ Value",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with\nbalance_4h_ts as (\n  select *\n  from (\n          select chain, vault_id,\n              time_bucket_gapfill('4h', datetime) as datetime,\n              --sum(balance_diff) as balance_diff,\n              locf(avg(token_balance)) as balance\n          from data_report.vault_investor_balance_diff_4h_snaps_3d_ts\n          -- make sure we select the previous snapshot to fill the graph\n          where datetime between ('${__from:date}'::TIMESTAMPTZ - interval '3d') and '${__to:date}'::TIMESTAMPTZ\n              and investor_address = evm_address_to_bytea('$investor_address')\n          group by 1,2,3\n  ) as t\n  where balance is not null\n)\nselect \n    b.datetime as time,\n    sum(\n        (\n          (b.balance::NUMERIC * vpt.avg_ppfs::NUMERIC) / POW(10, 18 + vpt.want_decimals)::NUMERIC\n        )\n        * vpt.avg_want_usd_value\n    ) as value\nfrom balance_4h_ts b\nleft join data_derived.vault_ppfs_and_price_4h_ts vpt \n    on b.chain = vpt.chain \n    and b.vault_id = vpt.vault_id\n    and b.datetime = vpt.datetime\n    and $__timeFilter(vpt.datetime)\nwhere vpt.vault_id is not null\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "$ amount per vault",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with\nbalance_4h_ts as (\n  select *\n  from (\n          select chain, vault_id,\n              time_bucket_gapfill('4h', datetime) as datetime,\n              locf(avg(token_balance)) as balance\n          from data_report.vault_investor_balance_diff_4h_snaps_3d_ts\n          -- make sure we select the previous snapshot to fill the graph\n          where datetime between ('${__from:date}'::TIMESTAMPTZ - interval '3d') and '${__to:date}'::TIMESTAMPTZ\n            and investor_address = evm_address_to_bytea('$investor_address')\n          group by 1,2,3\n  ) as t\n  where balance is not null\n)\nselect \n    b.datetime as time, \n    vpt.vault_id,\n    sum(\n        (\n          (b.balance::NUMERIC * vpt.avg_ppfs::NUMERIC) / POW(10, 18 + vpt.want_decimals)::NUMERIC\n        )\n        * vpt.avg_want_usd_value\n    ) as value\nfrom balance_4h_ts b\nleft join data_derived.vault_ppfs_and_price_4h_ts vpt \n    on b.chain = vpt.chain \n    and b.vault_id = vpt.vault_id\n    and b.datetime = vpt.datetime\n    and $__timeFilter(vpt.datetime)\nwhere vpt.vault_id is not null\ngroup by 1,2\norder by 1,2"
    }
   ]
  },
  {
   "title": "$ amount per vault (cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with\nbalance_4h_ts as (\n  select *\n  from (\n          select chain, vault_id,\n              time_bucket_gapfill('4h', datetime) as datetime,\n              locf(avg(token_balance)) as balance\n          from data_report.vault_investor_balance_diff_4h_snaps_3d_ts\n          -- make sure we select the previous snapshot to fill the graph\n          where datetime between ('${__from:date}'::TIMESTAMPTZ - interval '3d') and '${__to:date}'::TIMESTAMPTZ\n              and investor_address = evm_address_to_bytea('$investor_address')\n          group by 1,2,3\n  ) as t\n  where balance is not null\n)\nselect \n    b.datetime as time, \n    vpt.vault_id,\n    sum(\n        (\n          (b.balance::NUMERIC * vpt.avg_ppfs::NUMERIC) / POW(10, 18 + vpt.want_decimals)::NUMERIC\n        )\n        * vpt.avg_want_usd_value\n    ) as value\nfrom balance_4h_ts b\nleft join data_derived.vault_ppfs_and_price_4h_ts vpt \n    on b.chain = vpt.chain \n    and b.vault_id = vpt.vault_id\n    and b.datetime = vpt.datetime\n    and $__timeFilter(vpt.datetime)\nwhere vpt.vault_id is not null\ngroup by 1,2\norder by 1,2"
    }
   ]
  },
  {
   "title": "$ amount per vault (cumulative to 100%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with\nbalance_4h_ts as (\n  select *\n  from (\n          select chain, vault_id,\n              time_bucket_gapfill('4h', datetime) as datetime,\n              locf(avg(token_balance)) as balance\n          from data_report.vault_investor_balance_diff_4h_snaps_3d_ts\n          -- make sure we select the previous snapshot to fill the graph\n          where datetime between ('${__from:date}'::TIMESTAMPTZ - interval '3d') and '${__to:date}'::TIMESTAMPTZ\n              and investor_address = evm_address_to_bytea('$investor_address')\n          group by 1,2,3\n  ) as t\n  where balance is not null\n)\nselect \n    b.datetime as time, \n    vpt.vault_id,\n    sum(\n        (\n          (b.balance::NUMERIC * vpt.avg_ppfs::NUMERIC) / POW(10, 18 + vpt.want_decimals)::NUMERIC\n        )\n        * vpt.avg_want_usd_value\n    ) as value\nfrom balance_4h_ts b\nleft join data_derived.vault_ppfs_and_price_4h_ts vpt \n    on b.chain = vpt.chain \n    and b.vault_id = vpt.vault_id\n    and b.datetime = vpt.datetime\n    and $__timeFilter(vpt.datetime)\nwhere vpt.vault_id is not null\ngroup by 1,2\norder by 1,2"
    }
   ]
  }
 ]
}