{
 "title": "User transaction list debug",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "investor_address",
    "query": "0xbeEF1EFee5938C2bB2FD99F5fb7EE015C3D81c76"
   },
   {
    "name": "chains",
    "query": "select distinct chain from product"
   },
   {
    "name": "product_keys",
    "query": "select distinct product_key from product where product_id in (\n select product_id \n from beefy_investor_timeline_cache_ts\n where investor_id = $_investor_id\n)\nand product_id in (\n select product_id\n from product\n where chain in ($chains)\n)"
   },
   {
    "name": "_investor_id",
    "query": "select investor_id\nfrom investor\nwhere address = hexstr_to_bytea('$investor_address')"
   },
   {
    "name": "_product_ids",
    "query": "select product_id from product where product_key in ($product_keys)"
   }
  ]
 },
 "panels": [
  {
   "title": "investment_balance_ts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.chain,\n  p.product_key,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as product_name,\n  c.datetime,\n  c.block_number,\n  --c.price_feed_1_id,\n  --c.price_feed_2_id,\n  --c.pending_rewards_price_feed_id,\n  c.balance::text,\n  c.balance_diff::text\nFROM investment_balance_ts c\n  JOIN product p ON c.product_id = p.product_id\nWHERE\n  $__timeFilter(datetime)\n  and investor_id = $_investor_id\n  and c.product_id in ($_product_ids)\nORDER BY datetime desc\n"
    }
   ]
  },
  {
   "title": "investment_balance_ts with price_1_ts ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.chain,\n  p.product_key,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as product_name,\n  c.datetime,\n  c.block_number,\n  --c.price_feed_1_id,\n  --c.price_feed_2_id,\n  --c.pending_rewards_price_feed_id,\n  c.balance::text,\n  c.balance_diff::text,\n  pr.price::text as ppfs\nFROM investment_balance_ts c\n  JOIN product p ON c.product_id = p.product_id\n  JOIN price_ts pr on p.price_feed_1_id = pr.price_feed_id and c.datetime = pr.datetime and c.block_number = pr.block_number\nWHERE\n  $__timeFilter(c.datetime)\n  and investor_id = $_investor_id\n  and c.product_id in ($_product_ids)\nORDER BY c.datetime desc\n"
    }
   ]
  },
  {
   "title": "beefy_investor_timeline_cache_ts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.chain,\n  p.product_key,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as product_name,\n  c.datetime,\n  c.block_number,\n  --c.price_feed_1_id,\n  --c.price_feed_2_id,\n  --c.pending_rewards_price_feed_id,\n  c.balance,\n  c.balance_diff,\n  c.share_to_underlying_price,\n  c.underlying_balance,\n  c.underlying_diff,\n  c.underlying_to_usd_price,\n  c.usd_balance,\n  c.usd_diff\nFROM beefy_investor_timeline_cache_ts c\n  JOIN product p ON c.product_id = p.product_id\nWHERE\n  $__timeFilter(datetime)\n  and investor_id = $_investor_id\n  and c.product_id in ($_product_ids)\nORDER BY datetime desc\n"
    }
   ]
  }
 ]
}