{
 "title": "Debug user transaction",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product"
   },
   {
    "name": "investor_address",
    "query": "0x9a43e2d3f7d28f0bb8a6b5952dc563ab51b8cb55"
   },
   {
    "name": "product_keys",
    "query": "select product_key from product where chain = '$chain' and product_id in (select product_id from investment_balance_ts where investor_id in ($_investor_ids))"
   },
   { "name": "transaction_hash" },
   { "name": "block_number", "query": "21556814" },
   { "name": "product_address" },
   {
    "name": "_product_ids",
    "query": "select product_id\nfrom product\nwhere product_key in ($product_keys)\nand chain = '$chain'"
   },
   {
    "name": "_investor_ids",
    "query": "select investor_id\nfrom investor\nwhere lower(bytea_to_hexstr(address)) = lower('$investor_address')"
   },
   {
    "name": "_import_state_keys",
    "query": "  select 'product:investment:'|| product_id \n  from (select unnest(ARRAY[$_product_ids]::integer[]) as product_id) as t"
   }
  ]
 },
 "panels": [
  {
   "title": "Transaction stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "User transactions",
     "type": "table",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(datetime),\n  product_id,\n  balance,\n  balance_diff,\n  pending_rewards,\n  pending_rewards_diff,\n  investment_data\nFROM\n  investment_balance_ts\nWHERE\n  $__timeFilter(datetime)\n  and product_id in ($_product_ids)\n  and investor_id in ($_investor_ids)\norder by 1"
      }
     ]
    }
   ]
  },
  { "title": "Import stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Product import state",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "select now() - min(\"lastImportDate\"::timestamptz) as last_import_at,\n  coalesce(bool_or(is_in_retry_queue), false) as is_in_retry_queue,\n  coalesce(bool_or(is_covered), false) as is_covered\nfrom (\n  select import_key, \"lastImportDate\", \n    \"toRetry\", $block_number between (\"toRetry\"->>'from')::integer and (\"toRetry\"->>'to')::integer as is_in_retry_queue,\n    \"coveredRanges\", $block_number between (\"coveredRanges\"->>'from')::integer and (\"coveredRanges\"->>'to')::integer as is_covered,\n    import_data \n  from (\n    select import_key, \n    import_data->'ranges'->>'lastImportDate' as \"lastImportDate\",  \n    jsonb_array_elements(import_data->'ranges'->'toRetry') as \"toRetry\",\n    jsonb_array_elements(import_data->'ranges'->'coveredRanges') as \"coveredRanges\", \n    import_data\n    from import_state\n    where import_key in ($_import_state_keys)\n  ) as t\n) as t\ngroup by import_key"
    }
   ]
  },
  {
   "title": "Investor infos",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT 'investor_id' as column, investor_id::text as value from investor where investor_id in ($_investor_ids)\nunion all \nSELECT 'address' as column, bytea_to_hexstr(address)::text as value from investor where investor_id in ($_investor_ids)\nunion all\nSELECT 'investor_data' as column, investor_data::text as value from investor where investor_id in ($_investor_ids)"
    }
   ]
  },
  {
   "title": "Product Infos",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "select 'product_id' as column, product_id::text as value from product where product_id in ($_product_ids)\nunion all\nselect 'product_key' as column, product_key::text as value from product where product_id in ($_product_ids)\nunion all\nselect 'chain' as column, chain::text as value from product where product_id in ($_product_ids)\nunion all\nselect 'price_feed_1_id' as column, price_feed_1_id::text as value from product where product_id in ($_product_ids)\nunion all\nselect 'price_feed_2_id' as column, price_feed_2_id::text as value from product where product_id in ($_product_ids)\nunion all\nselect 'contract_address' as column, lower(coalesce(product_data->'vault'->>'contract_address',product_data->'boost'->>'contract_address'))::text as value from product where product_id in ($_product_ids)\nunion all\nselect 'product_data' as column, jsonb_pretty(product_data)::text as value from product where product_id in ($_product_ids)"
    }
   ]
  },
  {
   "title": "Investments at this block",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select * \nfrom investment_balance_ts\nwhere product_id in ($_product_ids)\nand block_number = $block_number;"
    }
   ]
  },
  {
   "title": "Product import state",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select import_key, \"lastImportDate\", \n  \"toRetry\", $block_number between (\"toRetry\"->>'from')::integer and (\"toRetry\"->>'to')::integer as is_in_retry_queue,\n  \"coveredRanges\", $block_number between (\"coveredRanges\"->>'from')::integer and (\"coveredRanges\"->>'to')::integer as is_covered,\n  import_data \nfrom (\n  select import_key, \n  import_data->'ranges'->'lastImportDate' as \"lastImportDate\",  \n  jsonb_array_elements(import_data->'ranges'->'toRetry') as \"toRetry\",\n  jsonb_array_elements(import_data->'ranges'->'coveredRanges') as \"coveredRanges\", \n  import_data\n  from import_state\n  where import_key in ($_import_state_keys)\n) as t;"
    }
   ]
  }
 ]
}