{
 "title": "Investor Activity (entries and exits)",
 "time": { "from": "2020-09-07T07:50:27.011Z", "to": "2022-07-05T10:09:44.175Z" },
 "panels": [
  { "title": "Investor activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distinct Investor Entry Or Exit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$__interval', datetime) as time,\n  distinct_count(rollup(hll_investor_address)) as investor_activity\nFROM data_report.vault_entry_exit_count_4h_ts\nwhere $__timeFilter(datetime)\ngroup by 1\nORDER BY 1 asc"
    }
   ]
  },
  {
   "title": "Investor Entry Or Exit by chain",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$__interval', datetime) as time,\n  chain,\n  distinct_count(rollup(hll_investor_address)) as investor_count\nFROM data_report.vault_entry_exit_count_4h_ts\nwhere $__timeFilter(datetime)\ngroup by 1,2\nORDER BY 1 asc"
    }
   ]
  },
  { "title": "Investor entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Distinct Investor Entry",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$__interval', datetime) as time,\n  distinct_count(rollup(hll_investor_entries)) as investor_entries\nFROM data_report.vault_entry_exit_count_4h_ts\nwhere $__timeFilter(datetime)\n  and hll_investor_entries is not null\ngroup by 1\nORDER BY 1 asc"
    }
   ]
  },
  {
   "title": "Investor Entries by chain",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n   chain,\n  distinct_count(rollup(hll_investor_entries)) as investor_entries\nFROM data_report.vault_entry_exit_count_4h_ts\nwhere $__timeFilter(datetime)\n  and hll_investor_entries is not null\ngroup by 1,2\nORDER BY 1 asc"
    }
   ]
  },
  {
   "title": "Investor exits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "Distinct Investor Exits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$__interval', datetime) as time,\n  distinct_count(rollup(hll_investor_exits)) as investor_exits\nFROM data_report.vault_entry_exit_count_4h_ts\nwhere $__timeFilter(datetime)\n  and hll_investor_exits is not null\ngroup by 1\nORDER BY 1 asc"
    }
   ]
  },
  {
   "title": "Investor Exit by chain",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n   chain,\n  distinct_count(rollup(hll_investor_exits)) as investor_exits\nFROM data_report.vault_entry_exit_count_4h_ts\nwhere $__timeFilter(datetime)\n  and hll_investor_exits is not null\ngroup by 1,2\nORDER BY 1 asc"
    }
   ]
  }
 ]
}