{
 "title": "Fee Reports by vault",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from data_raw.vault_harvest_1d_ts"
   },
   {
    "name": "vault_id",
    "query": "select distinct vault_id from data_raw.vault where chain = '$chain'"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate of all selected vaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Daily Fees Collected in WNative token",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(h.strategist_wnative_amount) as strategist_amount,\n    sum(h.beefy_wnative_amount * 0.86) as bifi_stakers_amount,\n    sum(h.beefy_wnative_amount * 0.14) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\nWHERE\n  $__timeFilter(h.datetime)\n  and h.chain = '$chain'\n  and h.vault_id in ($vault_id)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Fees Collected in WNative token",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\n\nSELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(sum(h.strategist_wnative_amount)) over (order by time_bucket('1d', h.datetime)) as strategist_amount,\n    sum(sum(h.beefy_wnative_amount * 0.86)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_amount,\n    sum(sum(h.beefy_wnative_amount * 0.14)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\nWHERE\n  $__timeFilter(h.datetime)\n  and h.chain = '$chain'\n  and h.vault_id in ($vault_id)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Fees collected in $ at the price of collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    time_bucket('1d', datetime) as datetime,\n    avg(usd_value) as avg_usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1, 2\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n  --sum(h.strategist_wnative_amount) * avg(avg_usd_value) as strategist_usd_amount,\n  --sum(h.beefy_wnative_amount) * avg(avg_usd_value)  as beefy_usd_amount,\n  --sum(sum(h.strategist_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_usd_amount,\n  --sum(sum(h.beefy_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as beefy_usd_amount\n  --sum(sum(h.strategist_wnative_amount)) over (order by time_bucket('1d', h.datetime)) as strategist_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.86)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.14)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_wnative_amount\n    sum(h.strategist_wnative_amount) * avg(avg_usd_value) as strategist_wnative_amount,\n    sum(h.beefy_wnative_amount * 0.86) * avg(avg_usd_value) as bifi_stakers_wnative_amount,\n    sum(h.beefy_wnative_amount * 0.14) * avg(avg_usd_value) as bifi_treasury_wnative_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.datetime = h.datetime and p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1\n"
    }
   ]
  },
  {
   "title": "Fees collected in $ at the price of collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    time_bucket('1d', datetime) as datetime,\n    avg(usd_value) as avg_usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1, 2\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n  --sum(h.strategist_wnative_amount) * avg(avg_usd_value) as strategist_usd_amount,\n  --sum(h.beefy_wnative_amount) * avg(avg_usd_value)  as beefy_usd_amount,\n  --sum(sum(h.strategist_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_usd_amount,\n  --sum(sum(h.beefy_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as beefy_usd_amount\n  --sum(sum(h.strategist_wnative_amount)) over (order by time_bucket('1d', h.datetime)) as strategist_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.86)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.14)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_wnative_amount\n    sum(sum(h.strategist_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_amount,\n    sum(sum(h.beefy_wnative_amount * 0.86) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_amount,\n    sum(sum(h.beefy_wnative_amount * 0.14) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.datetime = h.datetime and p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1\n"
    }
   ]
  },
  {
   "title": "Fees collected in $ at the price of today",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    last(usd_value, datetime) as usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(h.strategist_wnative_amount) * avg(usd_value) as strategist_amount,\n    sum(h.beefy_wnative_amount * 0.86) * avg(usd_value) as bifi_stakers_amount,\n    sum(h.beefy_wnative_amount * 0.14) * avg(usd_value) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Fees collected in $ at the price of collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    last(usd_value, datetime) as usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(sum(h.strategist_wnative_amount) * avg(usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_amount,\n    sum(sum(h.beefy_wnative_amount * 0.86) * avg(usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_amount,\n    sum(sum(h.beefy_wnative_amount * 0.14) * avg(usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "$vault_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "vault_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Daily Fees Collected in WNative token",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(h.strategist_wnative_amount) as strategist_amount,\n    sum(h.beefy_wnative_amount * 0.86) as bifi_stakers_amount,\n    sum(h.beefy_wnative_amount * 0.14) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\nWHERE\n  $__timeFilter(h.datetime)\n  and h.chain = '$chain'\n  and h.vault_id in ($vault_id)\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Fees Collected in WNative token",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "\n\nSELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(sum(h.strategist_wnative_amount)) over (order by time_bucket('1d', h.datetime)) as strategist_amount,\n    sum(sum(h.beefy_wnative_amount * 0.86)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_amount,\n    sum(sum(h.beefy_wnative_amount * 0.14)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\nWHERE\n  $__timeFilter(h.datetime)\n  and h.chain = '$chain'\n  and h.vault_id in ($vault_id)\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Fees collected in $ at the price of collection",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    time_bucket('1d', datetime) as datetime,\n    avg(usd_value) as avg_usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1, 2\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n  --sum(h.strategist_wnative_amount) * avg(avg_usd_value) as strategist_usd_amount,\n  --sum(h.beefy_wnative_amount) * avg(avg_usd_value)  as beefy_usd_amount,\n  --sum(sum(h.strategist_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_usd_amount,\n  --sum(sum(h.beefy_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as beefy_usd_amount\n  --sum(sum(h.strategist_wnative_amount)) over (order by time_bucket('1d', h.datetime)) as strategist_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.86)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.14)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_wnative_amount\n    sum(h.strategist_wnative_amount) * avg(avg_usd_value) as strategist_wnative_amount,\n    sum(h.beefy_wnative_amount * 0.86) * avg(avg_usd_value) as bifi_stakers_wnative_amount,\n    sum(h.beefy_wnative_amount * 0.14) * avg(avg_usd_value) as bifi_treasury_wnative_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.datetime = h.datetime and p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1\n"
      }
     ]
    },
    {
     "title": "Fees collected in $ at the price of collection",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    time_bucket('1d', datetime) as datetime,\n    avg(usd_value) as avg_usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1, 2\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n  --sum(h.strategist_wnative_amount) * avg(avg_usd_value) as strategist_usd_amount,\n  --sum(h.beefy_wnative_amount) * avg(avg_usd_value)  as beefy_usd_amount,\n  --sum(sum(h.strategist_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_usd_amount,\n  --sum(sum(h.beefy_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as beefy_usd_amount\n  --sum(sum(h.strategist_wnative_amount)) over (order by time_bucket('1d', h.datetime)) as strategist_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.86)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_wnative_amount,\n  --sum(sum(h.beefy_wnative_amount * 0.14)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_wnative_amount\n    sum(sum(h.strategist_wnative_amount) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_amount,\n    sum(sum(h.beefy_wnative_amount * 0.86) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_amount,\n    sum(sum(h.beefy_wnative_amount * 0.14) * avg(avg_usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.datetime = h.datetime and p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1\n"
      }
     ]
    },
    {
     "title": "Fees collected in $ at the price of today",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    last(usd_value, datetime) as usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(h.strategist_wnative_amount) * avg(usd_value) as strategist_amount,\n    sum(h.beefy_wnative_amount * 0.86) * avg(usd_value) as bifi_stakers_amount,\n    sum(h.beefy_wnative_amount * 0.14) * avg(usd_value) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Fees collected in $ at the price of collection",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "with price_1d as (\n  select --chain, \n    oracle_id,\n    last(usd_value, datetime) as usd_value\n  FROM data_raw.oracle_price_ts\n  where oracle_id in (\n    'WETH', -- arbitrum\n    'WETH', -- aurora\n    'AVAX', -- avax\n    'WBNB', -- bsc\n    'CELO', -- celo\n    'WCRO', -- cronos\n    'ROSE', -- emerald\n    'WFTM', -- fantom\n    'WFUSE', -- fuse\n    'ONE', -- harmony\n    'WHT', -- heco\n    'METIS', -- metis\n    'WGLMR', -- moonbeam\n    'MOVR', -- moonriver\n    'WETH', -- optimism\n    'WMATIC', -- polygon\n    'WSYS' -- syscoin\n  )\n  group by 1\n)\nSELECT\n  time_bucket('1d', h.datetime) as time,\n    sum(sum(h.strategist_wnative_amount) * avg(usd_value)) over (order by time_bucket('1d', h.datetime)) as strategist_amount,\n    sum(sum(h.beefy_wnative_amount * 0.86) * avg(usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_stakers_amount,\n    sum(sum(h.beefy_wnative_amount * 0.14) * avg(usd_value)) over (order by time_bucket('1d', h.datetime)) as bifi_treasury_amount\nFROM\n  data_raw.vault_harvest_1d_ts h\n     left join price_1d p on p.oracle_id = \n        case \n            when h.chain = 'arbitrum' then 'WETH'\n            when h.chain = 'aurora' then 'WETH'\n            when h.chain = 'avax' then 'AVAX'\n            when h.chain = 'bsc' then 'WBNB'\n            when h.chain = 'celo' then 'CELO'\n            when h.chain = 'cronos' then 'WCRO'\n            when h.chain = 'emerald' then 'ROSE'\n            when h.chain = 'fantom' then 'WFTM'\n            when h.chain = 'fuse' then 'WFUSE'\n            when h.chain = 'harmony' then 'ONE'\n            when h.chain = 'heco' then 'WHT'\n            when h.chain = 'metis' then 'METIS'\n            when h.chain = 'moonbeam' then 'WGLMR'\n            when h.chain = 'moonriver' then 'MOVR'\n            when h.chain = 'optimism' then 'WETH'\n            when h.chain = 'polygon' then 'WMATIC'\n            when h.chain = 'syscoin' then 'WSYS'\n            else null\n        end\nWHERE\n  $__timeFilter(h.datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\norder by 1"
      }
     ]
    }
   ]
  }
 ]
}