{
 "title": "TVL & investor count by vault",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from data_report.vault_stats_4h_ts;"
   },
   {
    "name": "vault_id",
    "query": "select distinct vault_id from data_report.vault_stats_4h_ts where chain = '$chain' "
   }
  ]
 },
 "panels": [
  { "title": "Aggregate of selection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Selection TVL in USD ($vault_id)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  sum(balance_usd_value) as total_balance_usd_value\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$vault_id approx investor count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  distinct_count(rollup(owner_address_hll)) as total_approx_owner_count\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All vaults data in the same charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Selection TVL in USD ($vault_id)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  vault_id,\n  sum(balance_usd_value) as total_balance_usd_value\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1, 2\nORDER BY 1"
      }
     ]
    },
    {
     "title": "$vault_id approx investor count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  vault_id,\n  distinct_count(rollup(owner_address_hll)) as total_approx_owner_count\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\ngroup by 1, 2\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "$vault_id TVL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "vault_id",
   "collapsed": true,
   "panels": [
    {
     "title": "$vault_id TVL in WANT",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  balance_want_value\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "$vault_id TVL in USD",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  balance_usd_value\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "$vault_id approx investor count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  distinct_count(owner_address_hll) as approx_owner_count\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain = '$chain'\n  and vault_id in ($vault_id)\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}