{
 "title": "TVL & distinct investor count by chain",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from data_report.chain_stats_4h_ts"
   }
  ]
 },
 "panels": [
  { "title": "All chains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total TVL",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  sum(balance_usd_value) tvl\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\ngroup by 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Total Approx distinct investor count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  approx_owner_address_count\nFROM data_report.all_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1\n"
    }
   ]
  },
  { "title": "By chain comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "TVL by chain",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  chain,\n  sum(balance_usd_value) tvl\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\ngroup by 1,2\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Investor count by chain",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  chain,\n  distinct_count(owner_address_hll) as approx_owner_address_count\nFROM data_report.vault_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\nORDER BY 1\n"
    }
   ]
  },
  { "title": "$chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "chain" },
  {
   "title": "$chain TVL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('4h', datetime) AS \"time\",\n  sum(balance_usd_value) tvl\nFROM data_report.chain_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\ngroup by 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "$chain Investor count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  distinct_count(owner_address_hll) as approx_owner_address_count\nFROM data_report.chain_stats_4h_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\nORDER BY 1\n"
    }
   ]
  }
 ]
}