{
 "title": "Price debug",
 "time": { "from": "2022-06-27T00:00:00.000Z", "to": "2022-06-28T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product"
   },
   {
    "name": "product_key",
    "query": "select distinct product_key from product where chain = '$chain'"
   },
   { "name": "interval", "query": "15m,1h,4h,1d,7d,14d,30d" },
   {
    "name": "_price_feed_1_id",
    "query": "select price_feed_1_id from product where product_key = '$product_key'"
   },
   {
    "name": "_price_feed_2_id",
    "query": "select price_feed_2_id from product where product_key = '$product_key'"
   }
  ]
 },
 "panels": [
  { "title": "price_ts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PPFS Candles",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n      time_bucket(INTERVAL '$interval', datetime) AS \"time\",\n      AVG(price) as price_avg,\n      MAX(price) as price_high,\n      MIN(price) as price_low,\n      FIRST(price, datetime) as price_open,\n      LAST(price, datetime) as price_close\nFROM price_ts\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_1_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LP Price Candles",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n      time_bucket(INTERVAL '$interval', datetime) AS \"time\",\n      AVG(price) as price_avg,\n      MAX(price) as price_high,\n      MIN(price) as price_low,\n      FIRST(price, datetime) as price_open,\n      LAST(price, datetime) as price_close\nFROM price_ts\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_2_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PPFS price points",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n      datetime AS \"time\",\n      price\nFROM price_ts\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_1_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LP Price points",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n      datetime AS \"time\",\n      price\nFROM price_ts\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_2_id\nORDER BY 1"
    }
   ]
  },
  { "title": "price_ts_cagg_1h", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "PPFS Candles",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n      price_avg,\n      price_high,\n      price_low,\n      price_open,\n      price_close\nFROM price_ts_cagg_1h\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_1_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LP Price Candles",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n      price_avg,\n      price_high,\n      price_low,\n      price_open,\n      price_close\nFROM price_ts_cagg_1h\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_2_id\nORDER BY 1"
    }
   ]
  },
  { "title": "price_ts_cagg_1d", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "PPFS Candles",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n      price_avg,\n      price_high,\n      price_low,\n      price_open,\n      price_close\nFROM price_ts_cagg_1d\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_1_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "LP Price Candles",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n      price_avg,\n      price_high,\n      price_low,\n      price_open,\n      price_close\nFROM price_ts_cagg_1d\nWHERE\n  $__timeFilter(datetime)\n  and price_feed_id = $_price_feed_2_id\nORDER BY 1"
    }
   ]
  }
 ]
}