{
 "title": "Raw Data Debug",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "label": "chain",
    "query": "arbitrum,aurora,avax,bsc,celo,cronos,emerald,fantom,fuse,harmony,heco,metis,moonbeam,moonriver,optimism,polygon,syscoin"
   },
   {
    "name": "oracle_id",
    "query": "select distinct oracle_id from data_raw.oracle_price_ts;"
   }
  ]
 },
 "panels": [
  {
   "title": "ERC 20 Transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Moo Transfers ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  chain as value,\n  count(*) as transfer_count\nFROM data_raw.erc20_transfer_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\nGROUP BY time_bucket('$__interval', datetime), chain, contract_address\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Vault Withdraws ",
     "type": "timeseries",
     "description": "Transfers where the \"to\" field is set to 0x0000...",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  chain as value,\n  count(*) as transfer_count\nFROM data_raw.erc20_transfer_ts\nWHERE\n  $__timeFilter(datetime)\n  and to_address = '\\x0000000000000000000000000000000000000000'\n  and chain in ($chain)\nGROUP BY time_bucket('$__interval', datetime), chain, contract_address\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Vault Deposits ",
     "type": "timeseries",
     "description": "Transfers where the from field is set to 0x0000...",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  chain as value,\n  count(*) as transfer_count\nFROM data_raw.erc20_transfer_ts\nWHERE\n  $__timeFilter(datetime)\n  and from_address = '\\x0000000000000000000000000000000000000000'\n  and chain in ($chain)\nGROUP BY time_bucket('$__interval', datetime), chain, contract_address\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "PPFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "PPFS data point count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  chain as value,\n  count(*) as ppfs_point_count\nFROM data_raw.vault_ppfs_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\nGROUP BY time_bucket('$__interval', datetime), chain, contract_address\nORDER BY 1"
      }
     ]
    },
    {
     "title": "PPFS  by contract (limited to 100 contracts)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  format_evm_address(contract_address) as value,\n  avg(ppfs) as avg_ppfs\nFROM data_raw.vault_ppfs_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\n  and contract_address in (\n    select distinct contract_address\n    from data_raw.vault_ppfs_ts\n    WHERE $__timeFilter(datetime)\n    and chain in ($chain)\n    order by contract_address desc\n    limit 100\n  )\nGROUP BY time_bucket('$__interval', datetime), contract_address\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Prices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  },
  {
   "title": "USD Prices  by oracle",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$__interval', datetime) as time,\n  oracle_id as value,\n  locf(avg(usd_value)) as avg_usd_value\nFROM data_raw.oracle_price_ts\nWHERE\n  $__timeFilter(datetime)\n  and oracle_id in ('$oracle_id')\nGROUP BY time_bucket_gapfill('$__interval', datetime), oracle_id\nORDER BY 1,2"
    }
   ]
  }
 ]
}