{
 "title": "RPC errors",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chains",
    "query": "select distinct chain from product"
   },
   {
    "name": "interval",
    "query": "15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$interval', datetime) AS \"time\",\n  chain,\n  count(*) as error_count\nFROM rpc_error_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chains)\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "RPC Error Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT chain, count(*) as error_count\nFROM rpc_error_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chains)\ngroup by chain"
    }
   ]
  },
  {
   "title": "RPC Errors by Chain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT chain, count(*) as error_count\nFROM rpc_error_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chains)\ngroup by chain"
    }
   ]
  },
  {
   "title": "RPC Errors by RPC",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT rpc_url, count(*) as error_count\nFROM rpc_error_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chains)\ngroup by rpc_url"
    }
   ]
  },
  {
   "title": "Last 500 errors",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM rpc_error_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chains)\nORDER BY datetime desc\nlimit 500"
    }
   ]
  }
 ]
}