{
 "title": "Transfers Overview",
 "time": { "from": "2021-12-13T08:37:20.675Z", "to": "2022-03-08T19:44:00.675Z" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "label": "chain",
    "query": "arbitrum,aurora,avax,bsc,celo,cronos,emerald,fantom,fuse,harmony,heco,metis,moonbeam,moonriver,optimism,polygon,syscoin"
   }
  ]
 },
 "panels": [
  {
   "title": "Moo Transfers ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  chain as value,\n  count(*) as transfer_count\nFROM beefy_raw.erc20_transfer_ts\nWHERE\n  $__timeFilter(datetime)\n  and chain in ($chain)\nGROUP BY time_bucket('$__interval', datetime), chain, contract_address\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Vault Deposits ",
   "type": "timeseries",
   "description": "Transfers where the from field is set to 0x0000...",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  chain as value,\n  count(*) as transfer_count\nFROM beefy_raw.erc20_transfer_ts\nWHERE\n  $__timeFilter(datetime)\n  and from_address = '\\x0000000000000000000000000000000000000000'\n  and chain in ($chain)\nGROUP BY time_bucket('$__interval', datetime), chain, contract_address\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Vault Withdraws ",
   "type": "timeseries",
   "description": "Transfers where the \"to\" field is set to 0x0000...",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', datetime) as time,\n  chain as value,\n  count(*) as transfer_count\nFROM beefy_raw.erc20_transfer_ts\nWHERE\n  $__timeFilter(datetime)\n  and to_address = '\\x0000000000000000000000000000000000000000'\n  and chain in ($chain)\nGROUP BY time_bucket('$__interval', datetime), chain, contract_address\nORDER BY 1"
    }
   ]
  }
 ]
}