{
 "title": "All products",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chains",
    "query": "select distinct chain from product"
   },
   {
    "name": "product_keys",
    "query": "select product_key from product where chain in ($chains)"
   }
  ]
 },
 "panels": [
  {
   "title": "Price Feeds Without a Product",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)\nfrom price_feed \nwhere price_feed_id not in (\n  select price_feed_1_id from product\n  union all\n  select price_feed_2_id from product\n)"
    }
   ]
  },
  {
   "title": "Price Feeds total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)\nfrom price_feed"
    }
   ]
  },
  {
   "title": "Total products",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*)\nfrom product" }
   ]
  },
  {
   "title": "All Products",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select product_id, product_key, price_feed_1_id, price_feed_2_id, jsonb_pretty(product_data)\nfrom product\nwhere \n  chain in ($chains)\n  and product_key in ($product_keys)"
    }
   ]
  }
 ]
}