{
 "title": "Gimmi ze data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product"
   },
   {
    "name": "product_keys",
    "query": "select product_key from product where chain = '$chain'"
   },
   {
    "name": "_product_ids",
    "query": "select product_id from product where product_key in ($product_keys)"
   }
  ]
 },
 "panels": [
  {
   "title": "Products",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Products",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\n  p.product_key,\n  p.product_data\nFROM\n  product p\nWHERE\n  p.product_id in ($_product_ids)"
      }
     ]
    },
    {
     "title": "Transfers",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\n  b.datetime, b.block_number,\n  p.chain,\n  p.product_key,\n  bytea_to_hexstr(i.address) as investor_address,\n  b.balance,\n  b.investment_data\nFROM\n  investment_balance_ts b\n  left join product p on b.product_id = p.product_id\n  left join investor i on b.investor_id = i.investor_id\nWHERE\n  b.product_id in ($_product_ids)"
      }
     ]
    }
   ]
  },
  { "title": "Transfers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Transfers",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  b.datetime, b.block_number,\n  p.chain,\n  p.product_key,\n  bytea_to_hexstr(i.address) as investor_address,\n  b.balance\n  --b.investment_data\nFROM\n  investment_balance_ts b\n  left join product p on b.product_id = p.product_id\n  left join investor i on b.investor_id = i.investor_id\nWHERE\n  b.product_id in ($_product_ids)"
    }
   ]
  },
  {
   "title": "PPFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "PPFS",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  pr.datetime,\n  pr.block_number,\n  pr.price\nFROM\n  price_ts pr\n  left join product p on p.price_feed_1_id = pr.price_feed_id\nWHERE\n  p.product_id in ($_product_ids)"
      }
     ]
    }
   ]
  },
  {
   "title": "Underlying Price",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Underlying price",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT\n  pr.datetime,\n  pr.block_number,\n  pr.price\nFROM\n  price_ts pr\n  left join product p on p.price_feed_2_id = pr.price_feed_id\nWHERE\n  p.product_id in ($_product_ids)"
      }
     ]
    }
   ]
  }
 ]
}