{
 "title": "Import Result per product (slow)",
 "time": { "from": "now-9M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product"
   },
   { "name": "include_eol", "query": "no, yes" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "product_keys",
    "query": "select product_key from product where chain = '$chain' and case when '$include_eol' = 'yes' then true else coalesce(product_data->'vault'->>'eol', product_data->'boost'->>'eol')::text = 'false' END"
   },
   { "name": "remove_product_key_prefixes", "query": "yes, no" },
   {
    "name": "_product_ids",
    "query": "select product_id from product where product_key in ($product_keys)"
   },
   {
    "name": "_price_feed_1_ids",
    "query": "select price_feed_1_id from product where product_id in ($_product_ids)"
   },
   {
    "name": "_min_block_number",
    "query": "\n  select min((i.import_data->>'contractCreatedAtBlock')::integer) as creation_block\n  from import_state i\n  left join product p on p.product_id = (i.import_data->>'productId')::integer and i.import_data->>'type' = 'product:investment'\n  where p.product_id in ($_product_ids)"
   },
   {
    "name": "_min_datetime",
    "query": "  select TO_CHAR(min((i.import_data->>'contractCreationDate')::timestamptz), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')\n  from import_state i\n  left join product p on p.product_id = (i.import_data->>'productId')::integer and i.import_data->>'type' = 'product:investment'\n  where p.product_id in ($_product_ids)"
   }
  ]
 },
 "panels": [
  { "title": "Transfers Import", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coverage (0 = not covered, 1 = success, 2 = error)",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "with chain_blocks as (\n  select \n    time_bucket_gapfill('$interval', datetime) as datetime,\n    interpolate(first(block_number, datetime)) as block_number\n  from block_ts\n  where chain = '$chain'\n  and datetime between ('$_min_datetime'::timestamptz - 2*('$interval'::interval)) and now() + 2*('$interval'::interval)\n  group by 1\n),\nimport_state_scope as (\n  select i.*, (i.import_data->>'productId')::integer as product_id, \n    jsonb_build_array(jsonb_build_object(\n      'from', (i.import_data->>'contractCreatedAtBlock')::integer,\n      'to', (select max(block_number) from block_ts where chain = '$chain')\n    )) as full_ranges,\n    i.import_data->'ranges'->'coveredRanges' as covered_ranges,\n    i.import_data->'ranges'->'toRetry' as error_ranges\n  from import_state i\n  where i.import_key in (\n    select 'product:investment:' || product_id\n    from unnest(ARRAY[$_product_ids]) as t(product_id)\n  ) \n),\nimport_state_ranges as (\n  select product_id, jsonb_array_elements(full_ranges) as range, 0 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(covered_ranges) as range, 1 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(error_ranges) as range, 2 as range_result\n  from import_state_scope\n),\nproduct_import_result_ts as (\n  select datetime, r.product_id, max(range_result) as range_result\n  from chain_blocks b\n  left join import_state_ranges r on b.block_number between (range->>'from')::integer and (range->>'to')::integer\n  group by 1, 2\n)\nselect\n  range_result::text,\n  count(*)\nfrom product_import_result_ts r\nwhere range_result is not null\ngroup by 1\n  "
    }
   ]
  },
  {
   "title": "Product without an import state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "select count(*) filter(where i.import_key is null) as missing, count(*) all\nfrom product p\nleft join import_state i on 'product:investment:' || p.product_id = i.import_key\nwhere p.product_id in ($_product_ids)"
    }
   ]
  },
  {
   "title": "Coverage (0 = not covered, 1 = success, 2 = error)",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "with chain_blocks as (\n  select \n    time_bucket_gapfill('$interval', datetime) as datetime,\n    interpolate(first(block_number, datetime)) as block_number\n  from block_ts\n  where chain = '$chain'\n  and datetime between ('$_min_datetime'::timestamptz - 2*('$interval'::interval)) and now() + 2*('$interval'::interval)\n  group by 1\n),\nimport_state_scope as (\n  select i.*, (i.import_data->>'productId')::integer as product_id, \n    jsonb_build_array(jsonb_build_object(\n      'from', (i.import_data->>'contractCreatedAtBlock')::integer,\n      'to', (select max(block_number) from block_ts where chain = '$chain')\n    )) as full_ranges,\n    i.import_data->'ranges'->'coveredRanges' as covered_ranges,\n    i.import_data->'ranges'->'toRetry' as error_ranges\n  from import_state i\n  where i.import_key in (\n    select 'product:investment:' || product_id\n    from unnest(ARRAY[$_product_ids]) as t(product_id)\n  ) \n),\nimport_state_ranges as (\n  select product_id, jsonb_array_elements(full_ranges) as range, 0 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(covered_ranges) as range, 1 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(error_ranges) as range, 2 as range_result\n  from import_state_scope\n),\nproduct_import_result_ts as (\n  select datetime, max(range_result) as range_result\n  from chain_blocks b\n  left join import_state_ranges r on b.block_number between (range->>'from')::integer and (range->>'to')::integer\n  group by 1\n)\nselect\n  r.datetime as time,\n  range_result as \"$chain\"\nfrom product_import_result_ts r\norder by datetime\n  "
    }
   ]
  },
  {
   "title": "Coverage (0 = not covered, 1 = success, 2 = error)",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "with chain_blocks as (\n  select \n    time_bucket_gapfill('$interval', datetime) as datetime,\n    interpolate(first(block_number, datetime)) as block_number\n  from block_ts\n  where chain = '$chain'\n  and datetime between ('$_min_datetime'::timestamptz - 2*('$interval'::interval)) and now() + 2*('$interval'::interval)\n  group by 1\n),\nimport_state_scope as (\n  select i.*, (i.import_data->>'productId')::integer as product_id, \n    jsonb_build_array(jsonb_build_object(\n      'from', (i.import_data->>'contractCreatedAtBlock')::integer,\n      'to', (select max(block_number) from block_ts where chain = '$chain')\n    )) as full_ranges,\n    i.import_data->'ranges'->'coveredRanges' as covered_ranges,\n    i.import_data->'ranges'->'toRetry' as error_ranges\n  from import_state i\n  where i.import_key in (\n    select 'product:investment:' || product_id\n    from unnest(ARRAY[$_product_ids]) as t(product_id)\n  ) \n),\nimport_state_ranges as (\n  select product_id, jsonb_array_elements(full_ranges) as range, 0 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(covered_ranges) as range, 1 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(error_ranges) as range, 2 as range_result\n  from import_state_scope\n),\nproduct_import_result_ts as (\n  select product_id, datetime, max(range_result) as range_result\n  from chain_blocks b\n  left join import_state_ranges r on b.block_number between (range->>'from')::integer and (range->>'to')::integer\n  group by 1,2\n)\nselect\n  r.datetime as time,\n  case \n    when '$remove_product_key_prefixes' = 'yes' then regexp_replace(regexp_replace(p.product_key, 'beefy:', ''), '$chain:', '')\n    else p.product_key\n  end as product_key,\n  range_result as \" \"\nfrom product_import_result_ts r\njoin product p on r.product_id = p.product_id\norder by datetime\n  "
    }
   ]
  },
  { "title": "PPFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Coverage (0 = not covered, 1 = success, 2 = error)",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "with chain_blocks as (\n  select \n    time_bucket_gapfill('$interval', datetime) as datetime,\n    interpolate(first(block_number, datetime)) as block_number\n  from block_ts\n  where chain = '$chain'\n  and datetime between ('$_min_datetime'::timestamptz - 2*('$interval'::interval)) and now() + 2*('$interval'::interval)\n  group by 1\n),\nimport_state_scope as (\n  select i.*, (i.import_data->>'productId')::integer as product_id, \n    jsonb_build_array(jsonb_build_object(\n      'from', (i.import_data->>'contractCreatedAtBlock')::integer,\n      'to', (select max(block_number) from block_ts where chain = '$chain')\n    )) as full_ranges,\n    i.import_data->'ranges'->'coveredRanges' as covered_ranges,\n    i.import_data->'ranges'->'toRetry' as error_ranges\n  from import_state i\n  where i.import_key in (\n    select 'price:feed:' || price_feed_id\n    from unnest(ARRAY[$_price_feed_1_ids]) as t(price_feed_id)\n  ) \n),\nimport_state_ranges as (\n  select product_id, jsonb_array_elements(full_ranges) as range, 0 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(covered_ranges) as range, 1 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(error_ranges) as range, 2 as range_result\n  from import_state_scope\n),\nproduct_import_result_ts as (\n  select datetime, r.product_id, max(range_result) as range_result\n  from chain_blocks b\n  left join import_state_ranges r on b.block_number between (range->>'from')::integer and (range->>'to')::integer\n  group by 1, 2\n)\nselect\n  range_result::text,\n  count(*)\nfrom product_import_result_ts r\nwhere range_result is not null\ngroup by 1\n  "
    }
   ]
  },
  {
   "title": "Product without an import state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "select count(*) filter(where i.import_key is null) as missing, count(*) all\nfrom product p\nleft join import_state i on 'price:feed:' || p.price_feed_1_id = i.import_key\nwhere p.product_id in ($_product_ids)"
    }
   ]
  },
  {
   "title": "Coverage (0 = not covered, 1 = success, 2 = error)",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 30 },
   "targets": [
    {
     "rawSql": "with chain_blocks as (\n  select \n    time_bucket_gapfill('$interval', datetime) as datetime,\n    interpolate(first(block_number, datetime)) as block_number\n  from block_ts\n  where chain = '$chain'\n  and datetime between ('$_min_datetime'::timestamptz - 2*('$interval'::interval)) and now() + 2*('$interval'::interval)\n  group by 1\n),\nimport_state_scope as (\n  select i.*, (i.import_data->>'productId')::integer as product_id, \n    jsonb_build_array(jsonb_build_object(\n      'from', (i.import_data->>'contractCreatedAtBlock')::integer,\n      'to', (select max(block_number) from block_ts where chain = '$chain')\n    )) as full_ranges,\n    i.import_data->'ranges'->'coveredRanges' as covered_ranges,\n    i.import_data->'ranges'->'toRetry' as error_ranges\n  from import_state i\n  where i.import_key in (\n    select 'price:feed:' || price_feed_id\n    from unnest(ARRAY[$_price_feed_1_ids]) as t(price_feed_id)\n  ) \n),\nimport_state_ranges as (\n  select product_id, jsonb_array_elements(full_ranges) as range, 0 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(covered_ranges) as range, 1 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(error_ranges) as range, 2 as range_result\n  from import_state_scope\n),\nproduct_import_result_ts as (\n  select datetime, max(range_result) as range_result\n  from chain_blocks b\n  left join import_state_ranges r on b.block_number between (range->>'from')::integer and (range->>'to')::integer\n  group by 1\n)\nselect\n  r.datetime as time,\n  range_result as \"$chain\"\nfrom product_import_result_ts r\norder by datetime\n  "
    }
   ]
  },
  {
   "title": "Coverage (0 = not covered, 1 = success, 2 = error)",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "with chain_blocks as (\n  select \n    time_bucket_gapfill('$interval', datetime) as datetime,\n    interpolate(first(block_number, datetime)) as block_number\n  from block_ts\n  where chain = '$chain'\n  and datetime between ('$_min_datetime'::timestamptz - 2*('$interval'::interval)) and now() + 2*('$interval'::interval)\n  group by 1\n),\nimport_state_scope as (\n  select i.*, (i.import_data->>'productId')::integer as product_id, \n    jsonb_build_array(jsonb_build_object(\n      'from', (i.import_data->>'contractCreatedAtBlock')::integer,\n      'to', (select max(block_number) from block_ts where chain = '$chain')\n    )) as full_ranges,\n    i.import_data->'ranges'->'coveredRanges' as covered_ranges,\n    i.import_data->'ranges'->'toRetry' as error_ranges\n  from import_state i\n  where i.import_key in (\n    select 'price:feed:' || price_feed_id\n    from unnest(ARRAY[$_price_feed_1_ids]) as t(price_feed_id)\n  ) \n),\nimport_state_ranges as (\n  select product_id, jsonb_array_elements(full_ranges) as range, 0 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(covered_ranges) as range, 1 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(error_ranges) as range, 2 as range_result\n  from import_state_scope\n),\nproduct_import_result_ts as (\n  select product_id, datetime, max(range_result) as range_result\n  from chain_blocks b\n  left join import_state_ranges r on b.block_number between (range->>'from')::integer and (range->>'to')::integer\n  group by 1,2\n)\nselect\n  r.datetime as time,\n  case \n    when '$remove_product_key_prefixes' = 'yes' then regexp_replace(regexp_replace(p.product_key, 'beefy:', ''), '$chain:', '')\n    else p.product_key\n  end as product_key,\n  range_result as \" \"\nfrom product_import_result_ts r\njoin product p on r.product_id = p.product_id\norder by datetime\n  "
    }
   ]
  },
  {
   "title": "Transfers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transfers counts",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 21, "x": 3, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket_gapfill('$interval', b.datetime) as time,\n  case \n    when '$remove_product_key_prefixes' = 'yes' then regexp_replace(regexp_replace(p.product_key, 'beefy:', ''), '$chain:', '')\n    else p.product_key\n  end as product_key,\n  count(*) as \" \"\nFROM\n  investment_balance_ts b\n  JOIN product p on b.product_id = p.product_id\nWHERE\n  $__timeFilter(b.datetime)\n  and p.chain = '$chain'\n  and p.product_id in ($_product_ids)\ngroup by 1,2\norder by 1,2"
      }
     ]
    }
   ]
  }
 ]
}