{
 "title": "Chain TVL",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product where chain not in ('harmony', 'heco', 'aurora', 'celo', 'emerald')"
   },
   { "name": "include_eol", "query": "no, yes" },
   {
    "name": "product_keys",
    "query": "select chain || ':' || case when product_data->'vault' is not null then 'vault' else 'boost' end || ':' || coalesce(product_data->'vault'->>'id', product_data->'boost'->>'id') || ' ' || product_key\nfrom product \nwhere chain = '$chain'\n and  CASE \n         WHEN '$include_eol' = 'yes' THEN true\n         ELSE coalesce(product_data->'boost', product_data->'vault')->>'eol' = 'false'\n    END"
   },
   {
    "name": "_product_ids",
    "query": "select product_id \nfrom product \nwhere product_key in ($product_keys)"
   }
  ]
 },
 "panels": [
  {
   "title": "Chain $TVL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with vault_tvls_ts as (\n  SELECT\n    time_bucket('1d', datetime) AS datetime,\n    product_id,\n    max(staked_underlying) as max_staked_underlying\n  FROM beefy_vault_stats_ts\n  WHERE\n    $__timeFilter(datetime)\n    and product_id in ($_product_ids)\n  group by 1, 2\n)\nselect \n  tvl.datetime as time,\n  sum(tvl.max_staked_underlying * p.price_avg) as \"tvl $chain\"\nFROM vault_tvls_ts tvl\nJOIN product pr on pr.product_id = tvl.product_id\nJOIN price_ts_cagg_1d p \n  on p.price_feed_id = pr.price_feed_2_id -- we need the underlying price\n  and p.datetime = tvl.datetime\n  and $__timeFilter(p.datetime) -- tell pg which scope we are interested in\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$TVL by vault",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with vault_tvls_ts as (\n  SELECT\n    time_bucket('1d', datetime) AS datetime,\n    product_id,\n    max(staked_underlying) as max_staked_underlying\n  FROM beefy_vault_stats_ts\n  WHERE\n    $__timeFilter(datetime)\n    and product_id in ($_product_ids)\n  group by 1, 2\n)\nselect \n  tvl.datetime as time,\n  coalesce(pr.product_data->'vault'->>'id', pr.product_data->'boost'->>'id') as beefy_id,\n  tvl.max_staked_underlying * p.price_avg as tvl\nFROM vault_tvls_ts tvl\nJOIN product pr on pr.product_id = tvl.product_id\nJOIN price_ts_cagg_1d p \n  on p.price_feed_id = pr.price_feed_2_id -- we need the underlying price\n  and p.datetime = tvl.datetime\n  and $__timeFilter(p.datetime) -- tell pg which scope we are interested in\nORDER BY 1"
    }
   ]
  },
  {
   "title": "tvl progress ${__from:date:iso} -> ${__to:date:iso}",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "with vault_staked_underlying_ts as (\n  SELECT\n    time_bucket('1d', datetime) AS datetime,\n    product_id,\n    max(staked_underlying) as max_staked_underlying\n  FROM beefy_vault_stats_ts\n  WHERE\n    $__timeFilter(datetime)\n    and product_id in ($_product_ids)\n  group by 1, 2\n),\nvault_tvl_ts as (\n  select \n    tvl.datetime,\n    tvl.product_id,\n    tvl.max_staked_underlying * p.price_avg as tvl\n  FROM vault_staked_underlying_ts tvl\n  JOIN product pr on pr.product_id = tvl.product_id\n  JOIN price_ts_cagg_1d p \n    on p.price_feed_id = pr.price_feed_2_id -- we need the underlying price\n    and p.datetime = tvl.datetime\n    and $__timeFilter(p.datetime) -- tell pg which scope we are interested in\n),\nvault_stats_ts_recent as (\n  SELECT\n      s.product_id,\n      last(s.datetime, s.datetime) AS \"datetime\",\n      last(s.tvl, s.datetime) as tvl\n    FROM vault_tvl_ts s\n    group by 1\n),\nvault_stats_ts_compare_to as (\n  SELECT\n      s.product_id,\n      first(s.datetime, s.datetime) AS \"datetime\",\n      first(s.tvl, s.datetime) as tvl\n    FROM vault_tvl_ts s\n    group by 1\n),\nvault_stats_ts_compared as (\n  select recent.product_id,\n    compare_to.datetime as compare_to_datetime,\n    recent.datetime as recent_datetime,\n    recent.datetime - compare_to.datetime as datetime_diff,\n    compare_to.tvl as compare_to_tvl,\n    recent.tvl as recent_tvl,\n    coalesce(recent.tvl, 0) - coalesce(compare_to.tvl, 0) as diff_tvl\n  from vault_stats_ts_recent recent\n  left join vault_stats_ts_compare_to compare_to using (product_id)\n)\nselect p.product_key,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as beefy_id,\n  ts.*\nfrom vault_stats_ts_compared ts\njoin product p using (product_id)\norder by ts.diff_tvl desc"
    }
   ]
  },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT \n  s.product_id,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as beefy_id,\n  s.datetime,\n  s.block_number,\n  s.vault_total_supply::varchar,\n  s.share_to_underlying_price::varchar,\n  s.staked_underlying::varchar,\n  s.underlying_total_supply::varchar,\n  s.underlying_capture_percentage\nFROM beefy_vault_stats_ts s\nJOIN product p using (product_id)\nWHERE\n  $__timeFilter(datetime)\n  and product_id in ($_product_ids)\nORDER BY 1"
    }
   ]
  }
 ]
}