{
 "title": "Investor counts with min balance (extra slow)",
 "time": { "from": "2021-06-11T00:00:00.000Z", "to": "2022-11-03T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product"
   },
   {
    "name": "product_keys",
    "query": "select product_key from product where chain in ($chain)"
   },
   { "name": "min_balance", "query": "0.1" },
   {
    "name": "_product_ids",
    "query": "select product_id from product where product_key in ($product_keys)"
   },
   {
    "name": "_min_datetime",
    "query": "  select TO_CHAR(min((i.import_data->>'contractCreationDate')::timestamptz), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')\n  from import_state i\n  left join product p on p.product_id = (i.import_data->>'productId')::integer and i.import_data->>'type' = 'product:investment'\n  where p.product_id in ($_product_ids)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Product Import state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with chain_blocks as materialized (\n  select \n    chain,\n    time_bucket_gapfill('$interval', datetime) as datetime,\n    interpolate(first(block_number, datetime)) as block_number\n  from block_ts\n  where chain in ($chain)\n  and datetime between ('$_min_datetime'::timestamptz - 2*('$interval'::interval)) and now() + 2*('$interval'::interval)\n  group by 1,2\n),\nlast_blocks as materialized (\n    select chain, last(block_number, datetime) max_block\n    from block_ts\n    where chain in ($chain)\n    group by chain\n),\nimport_state_scope as materialized (\n  select i.*, (i.import_data->>'productId')::integer as product_id, \n    jsonb_build_array(jsonb_build_object(\n      'from', (i.import_data->>'contractCreatedAtBlock')::integer,\n      'to', (lb.max_block)\n    )) as full_ranges,\n    i.import_data->'ranges'->'coveredRanges' as covered_ranges,\n    i.import_data->'ranges'->'toRetry' as error_ranges\n  from import_state i\n    left join product pr on i.import_key = 'product:investment:' || pr.product_id\n    left join last_blocks as lb on lb.chain = pr.chain\n  where i.import_key in (\n    select 'product:investment:' || product_id\n    from unnest(ARRAY[$_product_ids]) as t(product_id)\n  )\n),\nimport_state_ranges as (\n  select product_id, jsonb_array_elements(full_ranges) as range, 0 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(covered_ranges) as range, 1 as range_result\n  from import_state_scope\n  UNION ALL\n  select product_id, jsonb_array_elements(error_ranges) as range, 2 as range_result\n  from import_state_scope\n),\nproduct_import_result_ts as (\n  select product_id, datetime, max(range_result) as range_result\n  from chain_blocks b\n  left join import_state_ranges r on b.block_number between (range->>'from')::integer and (range->>'to')::integer\n  group by 1,2\n)\nselect\n  r.datetime as time,\n  p.product_key,\n  range_result as \" \"\nfrom product_import_result_ts r\njoin product p on r.product_id = p.product_id\norder by datetime\n  "
    }
   ]
  },
  {
   "title": "Holder count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from (\n\n  select bytea_to_hexstr(i.address) as address, sum(last_balance) total_balance\n  from (\n    SELECT investor_id, last(balance, datetime) as last_balance\n    FROM investment_balance_ts\n    where product_id in ($_product_ids)\n    group by investor_id\n  ) as b\n  left join investor i on b.investor_id = i.investor_id\n  group by 1\n  having sum(last_balance) > $min_balance\n  ) as t\n"
    }
   ]
  },
  {
   "title": "Holder size",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "targets": [
    {
     "rawSql": "select bytea_to_hexstr(i.address) as address, sum(last_balance) total_balance\nfrom (\n  SELECT investor_id, last(balance, datetime) as last_balance\n  FROM investment_balance_ts\n  where product_id in ($_product_ids)\n  group by investor_id\n) as b\nleft join investor i on b.investor_id = i.investor_id\ngroup by 1\nhaving sum(last_balance) > $min_balance\n"
    }
   ]
  },
  {
   "title": "log Holder size",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "select bytea_to_hexstr(i.address) as address, log(sum(last_balance)) total_balance\nfrom (\n  SELECT investor_id, last(balance, datetime) as last_balance\n  FROM investment_balance_ts\n  where product_id in ($_product_ids)\n  group by investor_id\n) as b\nleft join investor i on b.investor_id = i.investor_id\ngroup by 1\nhaving sum(last_balance) > $min_balance\n"
    }
   ]
  },
  {
   "title": "Holder list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select bytea_to_hexstr(i.address) as address, sum(last_balance) total_balance\nfrom (\n  SELECT investor_id, last(balance, datetime) as last_balance\n  FROM investment_balance_ts\n  where product_id in ($_product_ids)\n  group by investor_id\n) as b\nleft join investor i on b.investor_id = i.investor_id\ngroup by 1\nhaving sum(last_balance) > $min_balance\n"
    }
   ]
  }
 ]
}