{
 "title": "Product Balance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product"
   },
   {
    "name": "product_key",
    "query": "select product_key from product where chain = '$chain'"
   },
   {
    "name": "_product_id",
    "query": "select product_id from product where product_key = '$product_key'"
   }
  ]
 },
 "panels": [
  {
   "title": "Balances (accounting for ignored addresses)",
   "type": "table",
   "gridPos": { "h": 23, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with balance_ts as (\n  SELECT\n    investor_id,\n    last(balance, datetime) as balance,\n    last(datetime, datetime) as last_event,\n    last(block_number, datetime) as last_event_block_number\n  FROM investment_balance_ts\n  WHERE\n    product_id = $_product_id\n  group by 1\n  having last(balance, datetime) > 0\n)\nselect bytea_to_hexstr(i.address) as investor_address, balance::varchar as balance_txt, balance as balance_num, last_event, last_event_block_number\nfrom balance_ts\njoin investor i using (investor_id)"
    }
   ]
  },
  {
   "title": "Total holders (accounting for ignored addresses)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with balance_ts as (\n  SELECT\n    investor_id,\n    last(balance, datetime) as balance,\n    last(datetime, datetime) as last_event\n  FROM investment_balance_ts\n  WHERE\n    product_id = $_product_id\n  group by 1\n  having last(balance, datetime) > 0\n)\nselect count(*) from balance_ts"
    }
   ]
  },
  {
   "title": "Ignored addresses",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 17, "y": 7 },
   "targets": [
    {
     "rawSql": "select bytea_to_hexstr(address) as address \nfrom ignore_address \nwhere chain = '$chain'"
    }
   ]
  }
 ]
}