{
 "title": "Vault % Capture",
 "time": { "from": "now-9d", "to": "now-2d" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select distinct chain from product where chain not in ('harmony', 'heco', 'aurora', 'celo', 'emerald')"
   },
   { "name": "include_eol", "query": "no, yes" },
   {
    "name": "product_keys",
    "query": "select chain || ':' || case when product_data->'vault' is not null then 'vault' else 'boost' end || ':' || coalesce(product_data->'vault'->>'id', product_data->'boost'->>'id') || ' ' || product_key\nfrom product \nwhere chain = '$chain'\n and  CASE \n         WHEN '$include_eol' = 'yes' THEN true\n         ELSE coalesce(product_data->'boost', product_data->'vault')->>'eol' = 'false'\n    END"
   },
   {
    "name": "_product_ids",
    "query": "select product_id \nfrom product \nwhere product_key in ($product_keys)"
   }
  ]
 },
 "panels": [
  {
   "title": "% capture by vault",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1d', datetime) AS \"time\",\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as beefy_id,\n  max(underlying_capture_percentage)\nFROM beefy_vault_stats_ts\njoin product p using(product_id)\nWHERE\n  $__timeFilter(datetime)\n  and product_id in ($_product_ids)\ngroup by 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TVL by vault (beta)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with product_staked_underlying as (\n  SELECT\n    time_bucket('1d', ts.datetime) as datetime,\n    ts.product_id,\n    max(ts.staked_underlying * pr.price) as max_staked_value_usd\n  FROM beefy_vault_stats_ts ts\n  join product p using(product_id)\n  join price_ts pr on pr.price_feed_id = p.price_feed_2_id and time_bucket('1d', ts.datetime) = pr.datetime\n  WHERE\n    $__timeFilter(ts.datetime)\n    and product_id in ($_product_ids)\n  group by 1, 2\n)\nselect \n  ts.datetime as time,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as beefy_id,\n  sum(ts.max_staked_value_usd) as staked_value_usd\nfrom product_staked_underlying ts\njoin product p using(product_id)\ngroup by 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Chain TVL ",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "with product_staked_underlying as (\n  SELECT\n    time_bucket('1d', ts.datetime) as datetime,\n    ts.product_id,\n    max(ts.staked_underlying * pr.price) as max_staked_value_usd\n  FROM beefy_vault_stats_ts ts\n  join product p using(product_id)\n  join price_ts pr on pr.price_feed_id = p.price_feed_2_id and time_bucket('1d', ts.datetime) = pr.datetime\n  WHERE\n    $__timeFilter(ts.datetime)\n    and product_id in ($_product_ids)\n  group by 1, 2\n)\nselect \n  ts.datetime as time,\n  p.chain,\n  sum(ts.max_staked_value_usd) as staked_value_usd\nfrom product_staked_underlying ts\njoin product p using(product_id)\ngroup by 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "capture % progress ${__from:date:iso} -> ${__to:date:iso}",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "with vault_stats_ts_recent as (\n  SELECT\n      s.product_id,\n      last(s.datetime, s.datetime) AS \"datetime\",\n      last(s.underlying_capture_percentage, s.datetime) as underlying_capture_percentage\n    FROM beefy_vault_stats_ts s\n    WHERE\n      datetime < '${__to:date:iso}'\n      and product_id in ($_product_ids)\n    group by 1\n),\nvault_stats_ts_compare_to as (\n  SELECT\n      s.product_id,\n      last(s.datetime, s.datetime) AS \"datetime\",\n      last(s.underlying_capture_percentage, s.datetime) as underlying_capture_percentage\n    FROM beefy_vault_stats_ts s\n    WHERE\n      datetime < '${__from:date:iso}'\n      and product_id in ($_product_ids)\n    group by 1\n),\nvault_stats_ts_compared as (\n  select recent.product_id,\n    compare_to.datetime as compare_to_datetime,\n    recent.datetime as recent_datetime,\n    recent.datetime - compare_to.datetime as datetime_diff,\n    compare_to.underlying_capture_percentage as compare_to_underlying_capture_percentage,\n    recent.underlying_capture_percentage as recent_underlying_capture_percentage,\n    coalesce(recent.underlying_capture_percentage, 0) - coalesce(compare_to.underlying_capture_percentage, 0) as diff_underlying_capture_percentage\n  from vault_stats_ts_recent recent\n  left join vault_stats_ts_compare_to compare_to using (product_id)\n)\nselect p.product_key,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as beefy_id,\n  ts.*\nfrom vault_stats_ts_compared ts\njoin product p using (product_id)\norder by ts.diff_underlying_capture_percentage desc"
    }
   ]
  },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT \n  s.product_id,\n  coalesce(p.product_data->'vault'->>'id', p.product_data->'boost'->>'id') as beefy_id,\n  s.datetime,\n  s.block_number,\n  s.vault_total_supply::varchar,\n  s.share_to_underlying_price::varchar,\n  s.staked_underlying::varchar,\n  s.underlying_total_supply::varchar,\n  s.underlying_capture_percentage\nFROM beefy_vault_stats_ts s\nJOIN product p using (product_id)\nWHERE\n  $__timeFilter(datetime)\n  and product_id in ($_product_ids)\nORDER BY 1"
    }
   ]
  }
 ]
}